apiVersion: v1
kind: Service
metadata:
  name: gkx-backend-grpc
  namespace: gekaixing
spec:
  selector:
    app: gkx-backend-grpc
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
