apiVersion: v1
kind: Secret
metadata:
  name: gkx-backend-secret
  namespace: gekaixing
type: Opaque
stringData:
  AUTH_SECRET: replace-me
  DATABASE_URL: postgres://postgres:postgres@postgres:5432/gekaixing?sslmode=disable
